"""
Graph RAG: Graph-enhanced Retrieval Augmented Generation.

Implements two search strategies from Microsoft's GraphRAG paper:
- Local Search: Entity-focused, uses graph neighborhood
- Global Search: Community-level, uses summarized community reports

Also implements hybrid search combining graph traversal with vector retrieval.
"""

import json
from dataclasses import dataclass, field
from typing import Any, Optional

import networkx as nx
from loguru import logger
from openai import OpenAI
from tenacity import retry, stop_after_attempt, wait_exponential

from .config import config
from .knowledge_graph_builder import KnowledgeGraphBuilder


@dataclass
class EntityContext:
    """Context about an entity and its graph neighborhood."""
    entity_name: str
    entity_type: str
    properties: dict
    neighbors: list[dict]  # [{name, type, relationship, properties}]
    community_id: Optional[int] = None
    community_summary: Optional[str] = None


@dataclass
class CommunityReport:
    """A summarized report for a graph community."""
    community_id: int
    title: str
    summary: str
    entities: list[str]
    key_findings: list[str]
    relevance_score: float = 0.0


@dataclass
class GraphRAGAnswer:
    """Answer generated by GraphRAG with provenance."""
    answer: str
    search_type: str  # local, global, hybrid
    entities_used: list[str]
    communities_used: list[int]
    context_snippets: list[str]
    confidence: float


LOCAL_SEARCH_SYSTEM = """당신은 한국 기업 분석 전문가입니다.
주어진 그래프 컨텍스트(엔티티, 관계, 속성)와 문서 정보를 기반으로 질문에 답하세요.

답변 규칙:
- 컨텍스트에 있는 정보만 사용하세요
- 수치나 사실을 인용할 때는 출처를 명시하세요
- 불확실한 경우 명확히 표현하세요
- 한국어로 답변하세요
- 답변은 구체적이고 전문적이어야 합니다"""

GLOBAL_SEARCH_SYSTEM = """당신은 한국 기업 분석 전문가입니다.
여러 커뮤니티 요약 보고서를 바탕으로 포괄적이고 전략적인 분석을 제공하세요.

답변 규칙:
- 여러 커뮤니티의 정보를 통합하여 종합적 시각을 제공하세요
- 산업 트렌드, 경쟁 환경, 리스크를 포함하세요
- 구체적인 기업명, 수치, 시장 정보를 포함하세요
- 한국어로 답변하세요"""

COMMUNITY_SUMMARIZE_PROMPT = """다음 그래프 커뮤니티의 엔티티들을 분석하고 요약 보고서를 작성하세요.

커뮤니티 엔티티:
{entities}

커뮤니티 관계:
{relationships}

다음 JSON 형식으로 응답하세요:
{{
  "title": "커뮤니티 제목",
  "summary": "2-3문장 요약",
  "key_findings": ["발견 1", "발견 2", "발견 3"],
  "entity_names": ["엔티티1", "엔티티2"]
}}"""


class GraphRAG:
    """
    Graph RAG system combining Neo4j graph traversal with LLM generation.

    Based on Microsoft GraphRAG (2024) with adaptations for Korean company analysis.
    """

    def __init__(
        self,
        graph_builder: Optional[KnowledgeGraphBuilder] = None,
        vector_store=None,
    ):
        self.graph_builder = graph_builder or KnowledgeGraphBuilder()
        self.vector_store = vector_store  # MultimodalVectorStore, optional
        self._openai_client = None
        self._nx_graph: Optional[nx.Graph] = None
        self._community_reports: list[CommunityReport] = []

    @property
    def openai_client(self) -> OpenAI:
        if self._openai_client is None:
            self._openai_client = OpenAI(api_key=config.openai.api_key)
        return self._openai_client

    # --- Core Search Methods -------------------------------------------

    def local_search(
        self,
        query: str,
        entity_name: Optional[str] = None,
        k: int = 5,
    ) -> GraphRAGAnswer:
        """
        Entity-focused local search using graph neighborhood.

        1. Identifies relevant entities from the query
        2. Retrieves their graph neighborhoods
        3. Generates an answer from the local context

        Args:
            query: User question
            entity_name: Optional specific entity to focus on
            k: Number of entities to retrieve

        Returns:
            GraphRAGAnswer with local context
        """
        logger.info(f"Local search: {query[:80]}")

        # Step 1: Identify relevant entities
        if entity_name:
            entities = [entity_name]
        else:
            entities = self._extract_query_entities(query, k=k)

        # Step 2: Get entity contexts
        contexts = []
        for ent_name in entities[:k]:
            try:
                ctx = self.get_entity_context(ent_name)
                contexts.append(ctx)
            except Exception as e:
                logger.warning(f"Failed to get context for {ent_name}: {e}")

        # Step 3: Format context for LLM
        context_text = self._format_local_context(contexts)

        # Step 4: Generate answer
        answer_text = self.generate_answer(query, context_text, mode="local")

        return GraphRAGAnswer(
            answer=answer_text,
            search_type="local",
            entities_used=entities,
            communities_used=[],
            context_snippets=[context_text[:500]],
            confidence=0.8 if contexts else 0.3,
        )

    def global_search(
        self,
        query: str,
        top_communities: int = 3,
    ) -> GraphRAGAnswer:
        """
        Community-level global search using summarized reports.

        1. Retrieves all community summaries
        2. Ranks communities by relevance to query
        3. Generates a comprehensive answer from top communities

        Args:
            query: User question
            top_communities: Number of communities to use

        Returns:
            GraphRAGAnswer synthesized from community reports
        """
        logger.info(f"Global search: {query[:80]}")

        # Ensure community reports exist
        if not self._community_reports:
            self.build_community_summaries()

        # Rank communities by relevance
        ranked = self._rank_communities_for_query(
            query, top_k=top_communities
        )

        # Format community context
        context_parts = []
        community_ids = []
        for report in ranked:
            context_parts.append(
                f"## {report.title}\n{report.summary}\n"
                f"주요 발견:\n" + "\n".join(f"- {f}" for f in report.key_findings)
            )
            community_ids.append(report.community_id)

        context_text = "\n\n---\n\n".join(context_parts)

        # Generate answer
        answer_text = self.generate_answer(query, context_text, mode="global")

        return GraphRAGAnswer(
            answer=answer_text,
            search_type="global",
            entities_used=[
                e for r in ranked for e in r.entities[:3]
            ],
            communities_used=community_ids,
            context_snippets=[context_text[:500]],
            confidence=0.85 if ranked else 0.2,
        )

    def hybrid_search(
        self,
        query: str,
        use_vector: bool = True,
        k: int = 5,
    ) -> GraphRAGAnswer:
        """
        Hybrid search combining graph traversal and vector retrieval.

        Merges local graph context with vector-retrieved text chunks
        for the most complete answer.

        Args:
            query: User question
            use_vector: Whether to include vector store results
            k: Number of results per source

        Returns:
            GraphRAGAnswer combining graph and vector evidence
        """
        logger.info(f"Hybrid search: {query[:80]}")

        context_parts = []
        entities_used = []
        communities_used = []

        # 1. Graph local search context
        try:
            local_result = self.local_search(query, k=k)
            if local_result.context_snippets:
                context_parts.append(
                    "### 그래프 컨텍스트\n" + "\n".join(local_result.context_snippets)
                )
            entities_used.extend(local_result.entities_used)
        except Exception as e:
            logger.warning(f"Local search failed in hybrid: {e}")

        # 2. Vector search context
        if use_vector and self.vector_store is not None:
            try:
                vector_results = self.vector_store.hybrid_multimodal_search(
                    query, k=k
                )
                if vector_results:
                    vector_ctx = "\n\n".join(
                        f"[문서 {r.doc_id}] {r.text[:400]}"
                        for r in vector_results[:k]
                    )
                    context_parts.append("### 문서 컨텍스트\n" + vector_ctx)
            except Exception as e:
                logger.warning(f"Vector search failed in hybrid: {e}")

        # 3. Community context (brief)
        if self._community_reports:
            top_community = self._rank_communities_for_query(query, top_k=1)
            if top_community:
                report = top_community[0]
                context_parts.append(
                    f"### 커뮤니티 컨텍스트\n{report.title}: {report.summary}"
                )
                communities_used.append(report.community_id)

        combined_context = "\n\n".join(context_parts)
        answer_text = self.generate_answer(query, combined_context, mode="hybrid")

        return GraphRAGAnswer(
            answer=answer_text,
            search_type="hybrid",
            entities_used=entities_used,
            communities_used=communities_used,
            context_snippets=[combined_context[:600]],
            confidence=0.9 if context_parts else 0.2,
        )

    # --- Entity Context ------------------------------------------------

    def get_entity_context(self, entity_name: str) -> EntityContext:
        """
        Retrieve an entity and its immediate graph neighborhood.

        Args:
            entity_name: Name of the entity to retrieve

        Returns:
            EntityContext with properties and neighbors
        """
        # Get entity properties
        entity_query = """
        MATCH (n {name: $name})
        RETURN labels(n)[0] AS entity_type, properties(n) AS props
        LIMIT 1
        """
        result = self.graph_builder.run_cypher(
            entity_query, {"name": entity_name}
        )

        if not result:
            return EntityContext(
                entity_name=entity_name,
                entity_type="Unknown",
                properties={},
                neighbors=[],
            )

        entity_type = result[0].get("entity_type", "Unknown")
        props = result[0].get("props", {})

        # Get neighbors (1-hop)
        neighbor_query = """
        MATCH (n {name: $name})-[r]-(neighbor)
        RETURN
            neighbor.name AS neighbor_name,
            labels(neighbor)[0] AS neighbor_type,
            type(r) AS relationship,
            properties(neighbor) AS neighbor_props
        LIMIT 20
        """
        neighbors_raw = self.graph_builder.run_cypher(
            neighbor_query, {"name": entity_name}
        )

        neighbors = [
            {
                "name": row.get("neighbor_name", ""),
                "type": row.get("neighbor_type", ""),
                "relationship": row.get("relationship", ""),
                "properties": {
                    k: v for k, v in (row.get("neighbor_props") or {}).items()
                    if k not in ("updated_at", "created_at")
                },
            }
            for row in neighbors_raw
        ]

        return EntityContext(
            entity_name=entity_name,
            entity_type=entity_type,
            properties={
                k: v for k, v in props.items()
                if k not in ("updated_at", "created_at")
            },
            neighbors=neighbors,
        )

    def traverse_relationships(
        self,
        start_entity: str,
        depth: int = 2,
        rel_types: Optional[list[str]] = None,
    ) -> dict:
        """
        Traverse the graph from a starting entity up to a given depth.

        Args:
            start_entity: Name of starting node
            depth: Maximum traversal depth
            rel_types: Optional list of relationship types to follow

        Returns:
            Dict with 'nodes' and 'edges' lists
        """
        if rel_types:
            rel_filter = "|".join(rel_types)
            rel_clause = f"[r:{rel_filter}*1..{depth}]"
        else:
            rel_clause = f"[r*1..{depth}]"

        cypher = f"""
        MATCH (start {{name: $name}}){rel_clause}(end)
        RETURN
            start.name AS from_name,
            labels(start)[0] AS from_type,
            end.name AS to_name,
            labels(end)[0] AS to_type,
            [rel in r | type(rel)] AS rel_types
        """

        results = self.graph_builder.run_cypher(cypher, {"name": start_entity})

        nodes = set()
        edges = []
        for row in results:
            from_name = row.get("from_name", "")
            to_name = row.get("to_name", "")
            nodes.add((from_name, row.get("from_type", "")))
            nodes.add((to_name, row.get("to_type", "")))
            if row.get("rel_types"):
                edges.append({
                    "from": from_name,
                    "to": to_name,
                    "relationships": row["rel_types"],
                })

        return {
            "nodes": [{"name": n, "type": t} for n, t in nodes],
            "edges": edges,
        }

    # --- Community Detection & Summarization ---------------------------

    def build_community_summaries(self) -> list[CommunityReport]:
        """
        Detect graph communities and generate LLM summaries for each.

        Uses networkx community detection (Louvain or Girvan-Newman).
        Generates a natural language summary for each community.

        Returns:
            List of CommunityReport objects
        """
        logger.info("Building community summaries...")

        # Load graph into networkx
        self._nx_graph = self._load_graph_into_networkx()

        if self._nx_graph.number_of_nodes() == 0:
            logger.warning("Graph is empty, cannot build communities")
            return []

        # Detect communities
        communities = self._detect_communities(self._nx_graph)
        logger.info(f"Found {len(communities)} communities")

        reports = []
        for comm_id, node_names in enumerate(communities):
            if len(node_names) < 2:
                continue

            try:
                report = self._summarize_community(comm_id, node_names)
                reports.append(report)
            except Exception as e:
                logger.warning(f"Failed to summarize community {comm_id}: {e}")

        self._community_reports = reports
        logger.info(f"Generated {len(reports)} community reports")
        return reports

    def _load_graph_into_networkx(self) -> nx.Graph:
        """Export Neo4j graph to networkx for community detection."""
        G = nx.Graph()

        # Load nodes
        nodes = self.graph_builder.run_cypher("""
        MATCH (n)
        WHERE n.name IS NOT NULL
        RETURN n.name AS name, labels(n)[0] AS node_type
        """)
        for node in nodes:
            if node.get("name"):
                G.add_node(node["name"], node_type=node.get("node_type", ""))

        # Load edges
        edges = self.graph_builder.run_cypher("""
        MATCH (a)-[r]->(b)
        WHERE a.name IS NOT NULL AND b.name IS NOT NULL
        RETURN a.name AS from_name, b.name AS to_name, type(r) AS rel_type
        """)
        for edge in edges:
            if edge.get("from_name") and edge.get("to_name"):
                G.add_edge(
                    edge["from_name"],
                    edge["to_name"],
                    rel_type=edge.get("rel_type", ""),
                )

        logger.info(
            f"Loaded graph: {G.number_of_nodes()} nodes, "
            f"{G.number_of_edges()} edges"
        )
        return G

    def _detect_communities(self, G: nx.Graph) -> list[list[str]]:
        """Detect communities using Louvain algorithm."""
        if G.number_of_nodes() < 3:
            return [list(G.nodes())]

        try:
            from community import best_partition

            partition = best_partition(G)
            community_map: dict[int, list[str]] = {}
            for node, comm_id in partition.items():
                community_map.setdefault(comm_id, []).append(node)
            return list(community_map.values())

        except ImportError:
            logger.warning(
                "python-louvain not installed. Trying leiden algorithm..."
            )
            try:
                import igraph as ig
                import leidenalg

                ig_graph = ig.Graph.from_networkx(G)
                partition = leidenalg.find_partition(
                    ig_graph, leidenalg.ModularityVertexPartition
                )
                return [
                    [ig_graph.vs[i]["_nx_name"] for i in cluster]
                    for cluster in partition
                ]

            except ImportError:
                logger.warning(
                    "No community detection library available. "
                    "Using connected components."
                )
                communities = []
                for component in nx.connected_components(G):
                    communities.append(list(component))
                return communities

    @retry(
        stop=stop_after_attempt(3),
        wait=wait_exponential(multiplier=1, min=2, max=10),
    )
    def _summarize_community(
        self, comm_id: int, node_names: list[str]
    ) -> CommunityReport:
        """Generate a summary report for a community."""
        # Get entity details
        entities_info = []
        for name in node_names[:15]:  # Limit to avoid token overflow
            try:
                ctx = self.get_entity_context(name)
                entities_info.append(
                    f"{ctx.entity_type}: {name} "
                    f"({json.dumps(ctx.properties, ensure_ascii=False)[:200]})"
                )
            except Exception:
                entities_info.append(f"Entity: {name}")

        # Get relationships within community
        relationships_info = []
        if len(node_names) <= 20:
            for i, n1 in enumerate(node_names):
                for n2 in node_names[i + 1:]:
                    try:
                        rel_query = """
                        MATCH (a {name: $n1})-[r]-(b {name: $n2})
                        RETURN type(r) AS rel
                        """
                        rels = self.graph_builder.run_cypher(
                            rel_query, {"n1": n1, "n2": n2}
                        )
                        for rel in rels:
                            relationships_info.append(
                                f"{n1} --[{rel['rel']}]--> {n2}"
                            )
                    except Exception:
                        pass

        prompt = COMMUNITY_SUMMARIZE_PROMPT.format(
            entities="\n".join(entities_info),
            relationships="\n".join(relationships_info[:20]),
        )

        response = self.openai_client.chat.completions.create(
            model=config.openai.llm_model,
            messages=[
                {
                    "role": "system",
                    "content": "당신은 기업 지식 그래프 분석 전문가입니다.",
                },
                {"role": "user", "content": prompt},
            ],
            temperature=0.0,
            max_tokens=800,
            response_format={"type": "json_object"},
        )

        raw = response.choices[0].message.content or "{}"
        try:
            data = json.loads(raw)
        except json.JSONDecodeError:
            data = {}

        return CommunityReport(
            community_id=comm_id,
            title=data.get("title", f"커뮤니티 {comm_id}"),
            summary=data.get("summary", ""),
            entities=data.get("entity_names", node_names[:5]),
            key_findings=data.get("key_findings", []),
        )

    def _rank_communities_for_query(
        self, query: str, top_k: int = 3
    ) -> list[CommunityReport]:
        """Rank communities by relevance to a query using keyword matching."""
        if not self._community_reports:
            return []

        query_lower = query.lower()
        query_words = set(query_lower.split())

        scored = []
        for report in self._community_reports:
            report_text = (
                report.title + " " + report.summary + " " +
                " ".join(report.key_findings) + " " +
                " ".join(report.entities)
            ).lower()

            # Count query word matches
            score = sum(1 for w in query_words if w in report_text)
            score += sum(
                0.5 for entity in report.entities if entity.lower() in query_lower
            )

            report.relevance_score = score
            scored.append(report)

        scored.sort(key=lambda r: r.relevance_score, reverse=True)
        return scored[:top_k]

    # --- Entity Identification -----------------------------------------

    def _extract_query_entities(self, query: str, k: int = 5) -> list[str]:
        """
        Extract entity names from a query using LLM + graph lookup.
        """
        # Step 1: Try to find exact matches in graph
        result = self.graph_builder.run_cypher("""
        MATCH (n)
        WHERE n.name IS NOT NULL
        RETURN n.name AS name, labels(n)[0] AS type
        ORDER BY n.name
        """)
        graph_entities = [r["name"] for r in result if r.get("name")]

        # Step 2: Simple keyword matching
        matched = []
        for ent in graph_entities:
            if ent and ent in query:
                matched.append(ent)

        if len(matched) >= k:
            return matched[:k]

        # Step 3: LLM extraction if needed
        if graph_entities:
            candidates = ", ".join(graph_entities[:50])
            response = self.openai_client.chat.completions.create(
                model=config.openai.llm_model,
                messages=[
                    {
                        "role": "system",
                        "content": (
                            "다음 엔티티 목록에서 질문과 관련된 엔티티를 선택하세요. "
                            "JSON 형식으로 응답: {\"entities\": [\"이름1\", \"이름2\"]}"
                        ),
                    },
                    {
                        "role": "user",
                        "content": f"질문: {query}\n\n엔티티 목록: {candidates}",
                    },
                ],
                temperature=0.0,
                max_tokens=200,
                response_format={"type": "json_object"},
            )
            raw = response.choices[0].message.content or "{}"
            try:
                data = json.loads(raw)
                matched = data.get("entities", [])[:k]
            except Exception:
                pass

        return matched[:k] if matched else []

    # --- Answer Generation ---------------------------------------------

    @retry(
        stop=stop_after_attempt(3),
        wait=wait_exponential(multiplier=1, min=2, max=10),
    )
    def generate_answer(
        self,
        query: str,
        context: str,
        mode: str = "hybrid",
    ) -> str:
        """
        Generate a final answer using the LLM with provided context.

        Args:
            query: User question
            context: Retrieved context string
            mode: 'local', 'global', or 'hybrid'

        Returns:
            Generated answer string
        """
        system_prompt = (
            LOCAL_SEARCH_SYSTEM if mode == "local"
            else GLOBAL_SEARCH_SYSTEM if mode == "global"
            else LOCAL_SEARCH_SYSTEM  # hybrid uses local style
        )

        max_context = config.llm.max_tokens * 2  # ~2 chars per token estimate
        truncated_context = context[:max_context]

        response = self.openai_client.chat.completions.create(
            model=config.openai.llm_model,
            messages=[
                {"role": "system", "content": system_prompt},
                {
                    "role": "user",
                    "content": (
                        f"컨텍스트:\n{truncated_context}\n\n"
                        f"질문: {query}"
                    ),
                },
            ],
            temperature=config.llm.temperature,
            max_tokens=config.llm.max_tokens,
        )

        return response.choices[0].message.content or "답변을 생성할 수 없습니다."

    # --- Utilities -----------------------------------------------------

    def _format_local_context(self, contexts: list[EntityContext]) -> str:
        """Format entity contexts into a text block for the LLM."""
        parts = []
        for ctx in contexts:
            props_str = json.dumps(ctx.properties, ensure_ascii=False, indent=2)
            neighbors_str = "\n".join(
                f"  - {n['name']} ({n['type']}) --[{n['relationship']}]--"
                for n in ctx.neighbors[:10]
            )
            parts.append(
                f"### {ctx.entity_type}: {ctx.entity_name}\n"
                f"속성:\n{props_str}\n\n"
                f"관련 엔티티:\n{neighbors_str}"
            )
        return "\n\n---\n\n".join(parts)
